name: Add Results to Repository

on:
  workflow_run:
    workflows: [Java CI with]
    types:
      - completed

jobs:
  add_results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Results Directory
        run: |
          # Create a copy of the "results" directory
          cp -r results results_copy

      - name: Commit and Push Results Directory
        run: |
          git config --local user.email "vishal.ghoniya@iitgn.ac.in"
          git config --local user.name "Vishal 987595"

          # Add and commit the "results_copy" directory
          git add results_copy
          git commit -m "Add 'results' directory"
          git push

